## 1. Find dot product of two arrays.

In [1]:
import numpy as np

In [6]:
a = [2j, 3j]
b = [2j, 3j]
a = np.array(a)
b = np.array(b)
a.dot(b)

(-13+0j)

## 2. Create two arrays of 2-D and find dot product of it.

In [3]:
a = np.random.randint(1,100,(3,3))
b = np.random.randint(1,100,(3,3))
a.dot(b)

array([[1921, 3806, 3552],
       [2831, 5119, 1425],
       [3558, 7523, 9441]])

In [4]:
a

array([[27, 17, 15],
       [ 6, 71,  8],
       [61, 11, 50]])

In [5]:
b

array([[43, 82, 78],
       [35, 61,  3],
       [11, 37, 93]])

## 3. Find vector product of given array.

In [39]:
a = np.array([1+2j,3+4j])

b = np.array([5+6j,7+8j])

print(np.cross(a,b))
print(np.vdot(a,b))

-16j
(70-8j)


## 4. FIrst create given array withound using direct value insted use numpy utlities and then find inner product for given array.
a = [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11]]

b = [[12 13 14 15] [16 17 18 19] [20 21 22 23]]

In [32]:
a = np.linspace(0,11,12)
b = np.linspace(12,23,12)

In [33]:
a = a.reshape(4,3)
b = b.reshape(4,3)

In [34]:
print(a)
print(b)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]


In [40]:
np.inner(a,b)

(-18+68j)

## 5. Using given two array try to print out 3rd given array.
a = np.array(['a', 'b', 'c'], dtype=object) b = np.array([1,2,3])

output = [['a', 'aa', 'aaa'], ['b', 'bb', 'bbb'], ['c', 'cc', 'ccc']]

In [41]:
a = np.array(['a', 'b', 'c'], dtype=object) 
b = np.array([1,2,3])
c = np.multiply(a,b)

In [44]:
c = a.reshape(3,1)*b.reshape(1,3)

In [45]:
c

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

## 6. Solve the system of equations 3 x0 + x1 = 9 and x0 + 2 x1 = 8

In [46]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
np.linalg.solve(a,b)

array([2., 3.])

## 7. Check the following solution is right or wrong uisng numpy utilities.
2x+3y=8 3x+y=5

solution: x=1 , y=2

In [47]:
a = np.array([[2,3],[3,1]])
b = np.array([8,5])
np.linalg.solve(a,b)

array([1., 2.])

yes the solution is correct

## 9. Write a program to add two arrays of different shape.
sample input:

a=[0.0,10.0,20.0,30.0]

b=[1.0,2.0,3.0]

output:

[[ 1., 2., 3.],

[ 11., 12., 13.],

[ 21., 22., 23.],

[ 31., 32., 33.]]

In [48]:
a = np.array([0,10,20,30])
b = np.array([1,2,3])
a.reshape(4,1) + b.reshape(1,3)

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

## 10. Create a 3 * 3 array find it's diagonal using numpy utilities.

In [51]:
data = np.random.randint(1,15,(3,3))
np.diagonal(data)

array([8, 3, 1])

## 12. Create given array without using indexing.
a = [[4, 0, 0], [0, 4, 0], [0, 0, 4], [0, 0, 0], [4, 0, 0], [0, 4, 0], [0, 0, 4]]

In [53]:
a = np.identity(3)

In [54]:
null = np.zeros(3)

In [56]:
np.vstact([a,])

TypeError: vstack() takes 1 positional argument but 3 were given