## 1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [6]:
import numpy as np
data = np.random.randint(1,10,20)
print(data)
print(np.bincount(data))

[6 9 1 6 4 3 9 9 5 3 8 7 5 6 1 9 8 9 7 8]
[0 2 0 2 1 2 3 2 3 5]


## 2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [7]:
data = np.random.randint(1,10,9)
data.reshape(3,3)

array([[7, 8, 1],
       [9, 1, 9],
       [3, 6, 1]])

## 3. How to find the memory size of any array

In [8]:
print(data.size*data.itemsize,"bytes")

36 bytes


## 4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [9]:
data = np.ones((10,10))
data[1:-1,1:-1] = 0
print(data)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [10]:
data = np.ones((8,8))
data[1::2,::2] = 0
data[::2,1::2] = 0
data

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

## 6. Normalize a 5x5 random matrix.
normalization formula : ((a-mean(a))/std(a))

In [13]:
data = np.random.randint(1,50,(5,5))
(data-np.mean(data))/np.std(data)

array([[-0.86886997,  0.61062998,  0.20712999,  0.00538   , -1.27236995],
       [-0.33086999, -0.19636999, -1.27236995,  1.35037995, -0.93611996],
       [ 1.01412996, -0.93611996,  1.88837993,  1.61937994,  1.48487994],
       [-0.86886997,  1.68662994, -0.06187   , -0.93611996, -0.66711997],
       [-1.20511995,  0.07263   , -0.93611996,  0.40887998,  0.13987999]])

## 7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [130]:
data = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
for i in range(len(data)):
    if 3<data[i]<8:
        data[i] = -data[i]
        
data

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

## 8. How to get the dates of yesterday, today and tomorrow?

In [25]:
print("Yesterday: ",np.datetime64('today','D')-np.timedelta64(1,'D'))
print("Today: ",np.datetime64('today','D'))
print("Tomorrow: ",np.datetime64('today','D')+np.timedelta64(1,'D'))

Yesterday:  2020-02-13
Today:  2020-02-14
Tomorrow:  2020-02-15


## 9. Generate two arrays of size 2X4 & 3X3, find difference between them.

In [26]:
array1 = np.random.randint(1,10,(2,4))
array2 = np.random.randint(1,15,(3,3))
array1.reshape(1,2,1,4) - array2.reshape(3,1,3,1)

array([[[[ -2,  -1,   3,  -3],
         [  0,   1,   5,  -1],
         [ -4,  -3,   1,  -5]],

        [[ -2,   4,   5,  -3],
         [  0,   6,   7,  -1],
         [ -4,   2,   3,  -5]]],


       [[[ -6,  -5,  -1,  -7],
         [ -7,  -6,  -2,  -8],
         [-12, -11,  -7, -13]],

        [[ -6,   0,   1,  -7],
         [ -7,  -1,   0,  -8],
         [-12,  -6,  -5, -13]]],


       [[[ -8,  -7,  -3,  -9],
         [  1,   2,   6,   0],
         [ -3,  -2,   2,  -4]],

        [[ -8,  -2,  -1,  -9],
         [  1,   7,   8,   0],
         [ -3,   3,   4,  -4]]]])

## 10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?
['cat','cat',...,'rat','dog','dog','cat'...]

In [131]:
array = ['cat','dog','rat']
np.random.choice(array,100)

array(['rat', 'rat', 'rat', 'cat', 'cat', 'dog', 'rat', 'cat', 'cat',
       'rat', 'dog', 'cat', 'dog', 'rat', 'rat', 'dog', 'cat', 'cat',
       'dog', 'cat', 'dog', 'dog', 'dog', 'dog', 'cat', 'cat', 'cat',
       'rat', 'dog', 'cat', 'rat', 'dog', 'cat', 'rat', 'rat', 'cat',
       'cat', 'rat', 'dog', 'dog', 'cat', 'cat', 'dog', 'dog', 'rat',
       'cat', 'rat', 'cat', 'cat', 'cat', 'dog', 'cat', 'rat', 'dog',
       'cat', 'rat', 'rat', 'rat', 'dog', 'dog', 'cat', 'cat', 'rat',
       'cat', 'dog', 'cat', 'dog', 'rat', 'rat', 'dog', 'cat', 'rat',
       'cat', 'dog', 'rat', 'rat', 'rat', 'rat', 'rat', 'cat', 'dog',
       'dog', 'dog', 'dog', 'rat', 'rat', 'dog', 'dog', 'cat', 'dog',
       'rat', 'dog', 'dog', 'cat', 'dog', 'cat', 'rat', 'dog', 'cat',
       'cat'], dtype='<U3')

## 11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [47]:
vect = np.linspace(0,1,12)[1:-1]
vect

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 12. Given a two dimensional array, how to extract unique rows?

In [49]:
data = np.random.randint(0,50,(5,5))
print(data)
print(data[[1]])

[[ 0  9 21 47 43]
 [12 47 16  6 37]
 [26 35 15 19 40]
 [14  3 31 11 20]
 [35 37 19  1  3]]
[[12 47 16  6 37]]


## 13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

## 14. How to find the closest value (to a given scalar) in a vector?

In [53]:
vect = np.arange(100)
scalar = np.random.uniform(0,100)
print(vect)
print(scalar)
index = (np.abs(vect-scalar)).argmin()
print(index)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
57.56467210609966
58


## 15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [59]:
rand_vect = np.random.randint(0,10,(10,2))
x = rand_vect[:,0]
y=rand_vect[:,1]
x-y

array([ 0, -5, -7, -1,  2,  3, -4,  0, -7, -1])

## 16. How to sort an array by the nth column?

In [62]:
data = np.random.randint(0,100,(5,5))
print(data)
print(data[data[:,4].argsort()])

[[78 55 69 84 80]
 [85 43 78 71 31]
 [98 49 78 28 44]
 [98 78 54  8 33]
 [51 83 25 16 55]]
[[85 43 78 71 31]
 [98 78 54  8 33]
 [98 49 78 28 44]
 [51 83 25 16 55]
 [78 55 69 84 80]]


## 17.How to tell if a given 2D array has null columns?

In [66]:
data = np.random.randint(1,10,(5,5))
np.isnan(data)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

## 18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [68]:
print(data)
print(np.sum(data[:,-2:]))

[[9 7 2 7 5]
 [8 4 9 7 9]
 [2 7 9 3 8]
 [3 9 4 3 9]
 [6 3 2 5 4]]
60


## 19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [71]:
print(data)
for i in range(len(data)):
    data[:,i] += i+1
print(data)

[[10 10  7 14 14]
 [ 9  7 14 14 18]
 [ 3 10 14 10 17]
 [ 4 12  9 10 18]
 [ 7  6  7 12 13]]
[[11 12 10 18 19]
 [10  9 17 18 23]
 [ 4 12 17 14 22]
 [ 5 14 12 14 23]
 [ 8  8 10 16 18]]


## 20. Given a 1d array(size 100) of boolean values, identify total number of True in it.

In [133]:
data = np.random.choice([True,False],100)
np.count_nonzero(data)

47

## 21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [121]:
vect = np.array([1, 2, 3, 4, 5])
n = 3
new_vect = np.zeros(len(vect)+(len(vect)-1)*n)
print(new_vect)
new_vect[::n+1]=vect
print(new_vect)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## 22. How to swap two rows of an array?

In [93]:
data = data.reshape(10,10)
print(data)
data[[1,5]] = data[[5,1]]
print(data)

[[432 437 263  45 459 188 471 214 455 308]
 [200 430 410 185 253   7 100 344 361 107]
 [184 238 413 233 177 104 223 127  64 456]
 [115 297 268  63 182 170 245 385 489 276]
 [167  48 231 175   1 287  55 364 260 484]
 [350 222 243 485   2 280 266 164 453 165]
 [172 426 203 492 482 389 185 396 104 169]
 [345 127 249 441 175  24 435 451 353 243]
 [170 132 246 414 480 105 271 211 266 396]
 [ 25 311 342 140 437 170 436 483 496 380]]
[[432 437 263  45 459 188 471 214 455 308]
 [350 222 243 485   2 280 266 164 453 165]
 [184 238 413 233 177 104 223 127  64 456]
 [115 297 268  63 182 170 245 385 489 276]
 [167  48 231 175   1 287  55 364 260 484]
 [200 430 410 185 253   7 100 344 361 107]
 [172 426 203 492 482 389 185 396 104 169]
 [345 127 249 441 175  24 435 451 353 243]
 [170 132 246 414 480 105 271 211 266 396]
 [ 25 311 342 140 437 170 436 483 496 380]]


## 24. How to get n largest value of an array?

In [105]:
n = 2
data = np.random.randint(1,20,5)
print(data)
data.sort()
print(data[-n:])

[13  6 14 16 14]
[14 16]


## 25. Given two random arrays of shape 5X5, identify the common elements between them.

In [110]:
array1 = np.random.randint(1,20,(5,5))
array2 = np.random.randint(1,25,(5,5))
print(array1)
print(array2)
print(np.intersect1d(array1,array2))

[[19 11  3 16  6]
 [ 1  6  8 10  7]
 [ 2 12  4 15  2]
 [18  4  3 14 17]
 [12  4  9  7  4]]
[[10  8  2 10  1]
 [15 12  6  8 13]
 [16  4  6 22  6]
 [13  5 14 10 12]
 [ 2 22 19 16  3]]
[ 1  2  3  4  6  8 10 12 14 15 16 19]


## 26. How to get index of top two highest value in a 1d array?

In [115]:
data = np.random.randint(1,10,12)
print(data)
data.argsort()[-2:]

[1 3 4 9 2 1 3 1 4 5 5 5]


array([11,  3], dtype=int64)