## 1. Create an array and find sum of it.

In [1]:
import numpy as np

In [2]:
data = np.random.randint(1,50,(5,5))
data.sum()

633

In [3]:
data

array([[18,  6, 25, 25, 13],
       [36, 39, 19, 15, 15],
       [46, 12, 34, 34, 20],
       [26, 27, 48, 34, 39],
       [32, 10,  1, 19, 40]])

## 2. Find sin of given array.

In [4]:
np.sin(data)

array([[-0.75098725, -0.2794155 , -0.13235175, -0.13235175,  0.42016704],
       [-0.99177885,  0.96379539,  0.14987721,  0.65028784,  0.65028784],
       [ 0.90178835, -0.53657292,  0.52908269,  0.52908269,  0.91294525],
       [ 0.76255845,  0.95637593, -0.76825466,  0.52908269,  0.96379539],
       [ 0.55142668, -0.54402111,  0.84147098,  0.14987721,  0.74511316]])

## 3. Find mean of matrix along row and column.

In [5]:
print(data.mean(axis = 1))

[17.4 24.8 29.2 34.8 20.4]


In [6]:
data.mean(axis = 0)

array([31.6, 18.8, 25.4, 25.4, 25.4])

## 4. Find standard deviation of given array.

In [7]:
data.std()

12.366794249117271

## 5. Create a 3*3 matrix and print it's transpose matrix

In [8]:
data = np.random.randint(1,50,(3,3))
print(data)

[[45 16 21]
 [27  8 24]
 [27  4 24]]


In [9]:
data.transpose()

array([[45, 27, 27],
       [16,  8,  4],
       [21, 24, 24]])

## 6. Create an array of 3*3 and find index of max along both axis.

In [10]:
print(data)

[[45 16 21]
 [27  8 24]
 [27  4 24]]


In [11]:
data.argmax(axis = 1)

array([0, 0, 0], dtype=int64)

In [12]:
data.argmax(axis = 0)

array([0, 0, 1], dtype=int64)

## 7. find sum of two matrix.

In [13]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,50,(3,3))
print(a)
print("__________________")
print(b)
print("____________________")
print(np.add(a,b))

[[6 3 3]
 [7 6 9]
 [1 6 6]]
__________________
[[16 44  9]
 [27 40 40]
 [46 26 47]]
____________________
[[22 47 12]
 [34 46 49]
 [47 32 53]]


## 8. Find indexes of max element along axis=0 and axis=1 .

In [14]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,50,(3,3))
print(a)
print("__________________")
print(b)
print("____________________")
print(np.add(a,b))

[[6 1 1]
 [9 5 4]
 [9 2 7]]
__________________
[[21 42 10]
 [40  2 48]
 [36 35  6]]
____________________
[[27 43 11]
 [49  7 52]
 [45 37 13]]


## 9. Write a program to add two arrays of different shape.

In [15]:
Hint: Broadcasting Level: Medium sample input:

a=[0.0,10.0,20.0,30.0]

b=[1.0,2.0,3.0]

output:

[[ 1., 2., 3.],

[ 11., 12., 13.],

[ 21., 22., 23.],

[ 31., 32., 33.]]

SyntaxError: invalid syntax (<ipython-input-15-3e025b6fe769>, line 1)

In [27]:
a = np.array([0.0,10.0,20.0,30.0])
b = np.array([1.0,2.0,3.0])
a = a.reshape(4,1)
print(a)
print("_________________")
print(b)
print("__________________")
print(a+b)

[[ 0.]
 [10.]
 [20.]
 [30.]]
_________________
[1. 2. 3.]
__________________
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


## 10. Try to solve a array and print a array with indices which would sort the given array.

In [ ]:
sample input:

a = [3,1,8,2]

output:

[1,3,0,2]

In [28]:
a = [3,1,8,2]
np.argsort(a)

array([1, 3, 0, 2], dtype=int64)

## 11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.

In [32]:
a = np.random.randint(1,500,(4,4))
np.argsort(a)

array([[0, 1, 2, 3],
       [2, 0, 3, 1],
       [3, 2, 1, 0],
       [0, 1, 3, 2]], dtype=int64)

In [33]:
a

array([[ 84, 144, 166, 422],
       [117, 202,   9, 136],
       [477, 423, 188, 181],
       [ 78, 133, 475, 346]])

In [34]:
np.argsort(a,axis = 1)

array([[0, 1, 2, 3],
       [2, 0, 3, 1],
       [3, 2, 1, 0],
       [0, 1, 3, 2]], dtype=int64)

In [35]:
np.argsort(a,axis = 0)

array([[3, 3, 1, 1],
       [0, 0, 0, 2],
       [1, 1, 2, 3],
       [2, 2, 3, 0]], dtype=int64)

## 12. calculate multiplication of transpose and matrix itself of a 3*3 matrix.

In [36]:
a = np.random.randint(1,8,(3,3))
a

array([[7, 5, 4],
       [6, 7, 4],
       [4, 3, 1]])

In [38]:
trans = a.transpose()
trans

array([[7, 6, 4],
       [5, 7, 3],
       [4, 4, 1]])

In [44]:
np.multiply(a,trans)

array([[49, 30, 16],
       [30, 49, 12],
       [16, 12,  1]])

## 13. Find solution for given linear equation:

2x + 5y = 28 4x + 3*y = 81

In [ ]:
representing the above equation in matrix form:
    [[2, 5],
     [4, 3]] * [x,             =   [28,
                                    81]
                y]   
    
    let a = [[2, 5], [4, 3]]
    X = [x, y]
    b = [28, 81]
    Then X is given by ,
                        X = a^(-1)b

In [52]:
a = np.array([[2,5],[4,3]])

In [53]:
# to find inverse
inverse = np.linalg.inv(a)
print(inverse)

[[-0.21428571  0.35714286]
 [ 0.28571429 -0.14285714]]


In [55]:
a = np.matrix([[2,5],[4,3]])

In [57]:
a.I   # I is identity matrix

matrix([[-0.21428571,  0.35714286],
        [ 0.28571429, -0.14285714]])

In [59]:
b = np.array([28,81])
inverse*b

array([[ -6.        ,  28.92857143],
       [  8.        , -11.57142857]])

## 14. Find Rank, Trace, Inverse, Determinant of a given matrix.

In [72]:
A=[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
data = np.array(A)

In [73]:
np.linalg.matrix_rank(data)

1

In [74]:
np.trace(data)

6

In [75]:
np.linalg.inv(data)    

LinAlgError: Singular matrix

In [76]:
np.linalg.det(data)   

0.0

In [ ]:
A is singular matrix so, inverse doesn't exist.

## 15. Find cube of a mtrix.

In [77]:
data

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [78]:
data**3    # cube element wise

array([[ 1,  1,  1],
       [ 8,  8,  8],
       [27, 27, 27]], dtype=int32)

In [83]:
data = np.matrix(data)
data

matrix([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [84]:
data * data * data   # cube of the matrix

matrix([[ 36,  36,  36],
        [ 72,  72,  72],
        [108, 108, 108]])