## 1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [3]:
import numpy as np
print(np.version.version)
print(np.__config__)

1.16.4
<module 'numpy.__config__' from 'c:\\users\\manishkc\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\numpy\\__config__.py'>


## 2. Create a null vector of size 10 but the fifth value which is 1.

In [6]:
ten_zeros = np.zeros(10)
ten_zeros[4] = 1
print(ten_zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Create a vector with values ranging from 10 to 49.

In [7]:
vect = np.arange(10,50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 3. create two arrays and stack them vertically

In [8]:
a = np.random.randint(10,100,(5,4))
b = np.random.randint(10,100,(4,4))
c = np.vstack([a,b])
print(c)

[[57 94 41 25]
 [92 76 15 57]
 [20 13 50 53]
 [81 39 45 44]
 [81 58 88 85]
 [75 85 47 77]
 [13 92 82 43]
 [33 79 72 27]
 [32 13 99 51]]


## 4. Reverse a vector (first element becomes last).

In [10]:
vect = np.arange(10,50)
vect = vect[::-1]
print(vect)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## 5. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
mat = np.random.randint(0,9,(3,3))
print(mat)

[[7 1 1]
 [3 4 5]
 [3 1 5]]


## 6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
a = [1,2,0,0,4,0]
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


## 7. Create a 10x10 array with random values and find the minimum and maximum values.

In [17]:
a = np.random.randint(1,1000,(10,10))
print(a)
np.amin(a)

[[252 359 984 989 498 600 647 580 806  52]
 [898 595 599 316 290 737  15 441  25  62]
 [818 429 247 434 804 295 940 397 661 179]
 [138 200 218 487 796 141 615  55 368 575]
 [475 647 910 569 544 595 768 974 847 469]
 [108 253 914 511 357 277 810 975 673 799]
 [989 684 905 540  46 711 319 390 707  94]
 [665 740 826 828 238 270 632 680 916 753]
 [287  11 202 963 701 583 239 494 217  74]
 [591 299 785 754 459 418 731 149 829 492]]


11

In [18]:
np.amax(a)

989

## 8. Create a random vector of size 30 and find the mean value.

In [21]:
vect = np.random.randint(1,50,30)

In [22]:
print(vect)

[ 2 46 22 43 23  7 32 45 29 16 47 43 32 43 38 24  7 46 22 28  8 46 16 34
  1  2 31 45 22 38]


In [23]:
vect.mean()

27.933333333333334

## 9. Create a 2d array with 1 on the border and 0 inside

In [26]:
array = np.ones((10,10))

In [27]:
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 10. How to add a border (filled with 0's) around an existing array

In [37]:
array = np.ones((10,10))
array[[0,9]] = 0
array[:,[0,9]] = 0
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [38]:
matrix = np.zeros((5,5))
for i in range(1,len(matrix)):
    matrix[i][i-1] = i
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## 12. Create a 5*5 matrix with random values and normalize it.

In [46]:
random = np.random.rand(5,5)
print(random)
print("______________________________________________________________")
rand_min = np.amin(random)
rand_max = np.amax(random)
normalized_matrix = (random - rand_min) / (rand_max - rand_min)
print(normalized_matrix)

[[0.97255118 0.40726821 0.04988216 0.06769128 0.85880183]
 [0.16822655 0.6528508  0.04940001 0.05604598 0.41267089]
 [0.58862351 0.46529441 0.44888346 0.89429936 0.28657908]
 [0.28980544 0.99196135 0.25737273 0.36657111 0.77087939]
 [0.5427264  0.51196745 0.26254468 0.17035005 0.24651383]]
______________________________________________________________
[[9.79406992e-01 3.79676306e-01 5.11533178e-04 1.94059283e-02
  8.58725888e-01]
 [1.26067707e-01 6.40224427e-01 0.00000000e+00 7.05097643e-03
  3.85408211e-01]
 [5.72083197e-01 4.41238552e-01 4.23827541e-01 8.96386594e-01
  2.51632513e-01]
 [2.55055482e-01 1.00000000e+00 2.20646356e-01 3.36499161e-01
  7.65445545e-01]
 [5.23389167e-01 4.90755795e-01 2.26133475e-01 1.28320603e-01
  2.09125723e-01]]


## 13. How to find common values between two arrays

In [58]:
array1 = np.random.randint(10,16,(1,5))
print(array1)
print("__________________________________________________________")
array2 = np.random.randint(10,16,(1,5))
print(array2)
print("___________________________________________________________")
print(np.intersect1d(array1,array2))

[[13 13 11 11 15]]
__________________________________________________________
[[10 13 15 10 13]]
___________________________________________________________
[13 15]


## 14. Consider a generator function that generates 10 integers and use it to build an array

In [108]:
def generate_fibonacci(n):
    """
    This function is a generator funciton which will generate fibonacci numbers.
    """
    first_num = 0
    sec_num = 1 
    while n:
        next_num = first_num + sec_num
        yield next_num
        first_num,sec_num = sec_num,next_num
        n -= 1
        

array = np.fromiter(generate_fibonacci(10), dtype = float)
print(array)

[ 1.  2.  3.  5.  8. 13. 21. 34. 55. 89.]


## 15. Subtract the mean of each row of a matrix

In [111]:
a = np.random.rand(5,6)
print(a)
print("_________________________________________")
for item in a:
    row_mean = np.mean(item)
    print(row_mean)
    a -= row_mean
    print(a)
    print("________________________________________________________________________________________")
    
# if the question is to subtract the mean of each row from row's respective elements:
    
print(a - a.mean(axis = 1,keepdims = True))

[[0.06063114 0.54919737 0.6546484  0.94823036 0.42136849 0.59354975]
 [0.53499595 0.76897938 0.8437651  0.65050587 0.32670641 0.09832407]
 [0.45537802 0.40651796 0.21548132 0.0284295  0.69891557 0.98485694]
 [0.18400947 0.89887824 0.82504526 0.11015901 0.59681532 0.84823442]
 [0.86307977 0.54675021 0.07936609 0.43514162 0.94260322 0.58033286]]
_________________________________________
0.5379375858883096
[[-0.47730645  0.01125979  0.11671082  0.41029277 -0.11656909  0.05561216]
 [-0.00294164  0.23104179  0.30582751  0.11256828 -0.21123118 -0.43961352]
 [-0.08255957 -0.13141963 -0.32245626 -0.50950809  0.16097799  0.44691936]
 [-0.35392812  0.36094065  0.28710768 -0.42777857  0.05887774  0.31029684]
 [ 0.32514218  0.00881262 -0.4585715  -0.10279597  0.40466564  0.04239528]]
________________________________________________________________________________________
-0.0007247905884108508
[[-0.47658166  0.01198458  0.11743561  0.41101756 -0.1158443   0.05633696]
 [-0.00221685  0.23176658  0.3

## 16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [100]:
a = np.random.randint(1,10,(1,3))
b = np.random.randint(1,10,(3,1))
print(a)
print(b)
print("___________________")
print(sum(a,b))

[[4 9 8]]
[[4]
 [2]
 [9]]
___________________
[[ 8 13 12]
 [ 6 11 10]
 [13 18 17]]


## 17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [94]:
vect = np.linspace(5,50,10)

In [95]:
print(vect)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
